image: "registry.gitlab.com/gitlab-org/gitlab-build-images:alpine-helm"

variables:
  SAST_DISABLE_DIND: "true"
  SEARCH_MAX_DEPTH: 99

include:
  - template: SAST.gitlab-ci.yml

stages:
  - build
  - test
  - release

compile_manifests:
  stage: build
  script:
    - mkdir manifests
    - helm init --client-only
    - helm dependency build
    - helm template -f values.yaml --output-dir manifests .
  artifacts:
    paths:
      - manifests

lint:
  stage: test
  script:
    - helm lint .

kubesec-sast:
  extends: .analyzer
  needs: ["compile_manifests"]
  image:
    name: "registry.gitlab.com/gitlab-org/security-products/analyzers/kubesec:add-kubesec-analyzer"

release-chart:
  stage: release
  script:
    - curl --fail --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/2860651/trigger/pipeline
  only:
    - master@gitlab-org/charts/auto-deploy-app
